### ISSUE TITLE
[conan] recipe not working with conan v2

### ISSUE THREAD

**Issue by pcorbineau** [cross-language-cpp/djinni-generator#148]
Since the new update from conan 1.X -> 2.X, the recipe of **djinni-generator** and **djinni-support-lib** are not working anymore.

Are you aware about it ?

**Comment by a4z** [comment]
Yes, I am aware of it. 
I am not very happy about the Conan 2 situation, [as I documented here](https://a4z.gitlab.io/blog/2023/04/17/Conan2-not-just-great.html)

In fact, I am unsure if I continue to support those recipes because I am unsure if I will be a future Conan (2) user.
So if a quick fix is required, we need to hope that someone from the community, either Djinni or Conan, will fix that.

(The changes to port the recipes to conan 2 should actually be not that much)

Howerver, that reminds me we have some CIs that need to pin the conan version to 1.x ... but that might be an other issue

**Comment by a4z** [comment]
I do not plan to re-add a recipe myself since we have brew for Mac and scoop for Windows,  and for Linux a simple download is sufficient. 
For the support-lib, I have another alterative in mind.

But if anyone wants to maintain the Conan recipes, I would help, but that happens in the [CCI](https://github.com/conan-io/conan-center-index) and not here
