### ISSUE TITLE
documentation update for next release (0.2.1 or  0.3.0 or 1.0.0)

### ISSUE THREAD

**Issue by a4z** [cross-language-cpp/djinni-generator#23]
For the upcoming release we need docs for

* #14 , the applied changes in #22 
* #20  and #21 
* and better docu for #11 , so this issue can be seen as done (for now)

**Comment by jothepro** [comment]
Note: In #22 I forgot to mention that every change to the parameter documentation in `Main.scala` should also be made to the [cli-usage](https://github.com/cross-language-cpp/djinni-generator/blob/main/docs/cli-usage.md) docs, because the docs resemble a copy of what the `--help` command outputs. So we should not forget to also document the new default values there.

**Comment by a4z** [comment]
I think this has also be sovled in various docu update , like #22 and/or #28 , therefore I think this issue can be closed
