### ISSUE TITLE
Add --objc-private-header-out

### ISSUE THREAD

**Issue by richey-v** [cross-language-cpp/djinni-generator#30]
The addition of `--objc-header-out` in [Release v0.3.0](https://github.com/cross-language-cpp/djinni-generator/releases/tag/v0.3.0) is great!  I would be helped greatly if there was a way to split out the placement of the private Objective-C headers (the `+Private.h` ones).  

The motivation for this is to avoid exposing internal (private) symbols.  As-is, when creating a Framework with the Djinni-generated headers as the public headers, I have to do a lot of shenanigans to filter the Objective-C headers and to create multiple build targets.  I believe that adding an additional option (such as the proposed `--objc-private-header-out` from the title of this issue) or some other mechanism would be very helpful.

**Comment by a4z** [comment]
It is now possible to generate all public headers into a ../include/ directory ..
so the public interface is separated from the private one.

all the +Private.h headers are Objective-C++ headers, it think,  and they need never to be exposed
There is the `--objcpp-out` option, that will generate the ObjectiveC++ implementation and include files there, so you can already generate them to an extra location, it's just defaulted to the `--objc-out`. 
That that's why they are, so far, side by side.

is this not enough ?

**Comment by richey-v** [comment]
Thanks @a4z , you are correct... I overlooked that `--objc-header-out` was for the public headers (only) and finally tested and confirmed all that you mention.

**Comment by a4z** [comment]
Thank you for the feedback, Will!
