### ISSUE TITLE
syntax error in generated C++ code for JNI

### ISSUE THREAD

**Issue by Neusoft-Technology-Solutions** [cross-language-cpp/djinni-generator#41]
the generated C++ code for JNI contains stray ";" characters in places where the C++ syntax does not allow them.

the fix is trivial, we will upload a pull request to fix this in a minute

**Comment by Neusoft-Technology-Solutions** [comment]
fixed by
https://github.com/cross-language-cpp/djinni-generator/pull/42

**Comment by a4z** [comment]
Thank you for the fix, @Neusoft-Technology-Solutions , 
out of interest, may I ask what you are using to substitute shared_ptr ? 
some boost pointer ? 

Reason why I am asking, as you see there are many option in djinni, and some influence the code generation and have no unit test, so it's interesting to get some feeling over time what would be nice to have.
and the second reason is, I am simply curious :-)

**Comment by Neusoft-Technology-Solutions** [comment]
Sure! We just started experimenting with Djinni and for now have used the Dropbox implementation (https://github.com/dropbox/nn) as seen in some examples we found.

We actually had an initial quick scan through boost (which we use in most of our projects), but failed to find anything suitable. That aside, we haven't looked around for alternatives yet.

Is there a reason not to use the Dropbox implementation? Or do you know better alternatives?

**Comment by a4z** [comment]
Thank you for your answer @Neusoft-Technology-Solutions !

The only `not_null` pointer I am aware of, and I used (but not together with djinni), is that one from the Microsoft GSL library
https://github.com/microsoft/GSL
This one works good, and there is also a `strict_not_null` in the GSL, but that I have not used so far.

I guess these might be better, at least in the sense that they are still actively supported and much more tested because they have a wide user base.
