### ISSUE TITLE
Unit-Tests in djinni-support-lib can not be executed without a generator release.

### ISSUE THREAD

**Issue by jothepro** [cross-language-cpp/djinni-generator#44]
In #43 a big new feature is introduced: Python support for djinni.

Because djinni has been split into components, we do now face a problem while introducing the big new feature that includes big changes in both generator & support-lib:

The changes in the generator need to be released, otherwise it cannot be pulled as dependency in the support-lib to execute the unit tests. Once the generator is released, the unit-tests in the support-lib repository can test if the generated code compiles & works.
If theses test fails because of an error in the generator implementation, a hotfix needs to be made in the generator and the fix has to be released again.

From my point of view this should not be a problem in general, as all things should be tested locally before being pushed to the generator/support-lib repository anyways.The tests in github action should just be there to verify that everything is fine.

But in reality things go wrong, and situations like this may get nasty, if multiple patches need to be made in the generator for some unexpected reason. As a maintainer I think we should discuss options on how to reduce this hard dependency when introducing big features that require changes in both components.

**Comment by a4z** [comment]
To start the discussion, here something, maybe we can iterate on it

1) a merge into master generate a djinni binary, djinni-latest , and this is used
since this is tied to a commit, and the commit sha could be reflected in the version, there is some idea what this includes, if this info is ever needed.
And having a latest,  rolling release, available is common practice. Use at your own risk.

2) PRs for support lib has some way to know which generator to use. Which way this is, I do not know at the moment ...

**Comment by jothepro** [comment]
Theoretically you can always download a canary build from the latest github actions run: 

<img width="500" src="https://user-images.githubusercontent.com/21294002/115145986-e1261b00-a054-11eb-826f-fa3ea72f1623.png">

https://github.com/cross-language-cpp/djinni-generator/actions/runs/760704611

Each "CI" workflow creates an artifact with the djinni binary.

But it may be hard to get the artifact by using the api, afaik there is no endpoint for the "latest" action/artifact.

**Comment by a4z** [comment]
I think we should move that into the discussion part, since it does not seem there will be any action in reasonable time.
Also, the problem is not really a problem that stops something, it is more an inconvenience, that delays the pipeline if we run into the situation that there is a dependency. 

I think what we actually would need might be something like that
https://docs.gitlab.com/ee/ci/pipelines/multi_project_pipelines.html
and/or that
https://docs.gitlab.com/ee/ci/yaml/#cross-project-artifact-downloads-with-needs

not sure if gh action provides something similar
