### ISSUE TITLE
Recommend building with run-time QA instrumentation, at least for testing

### ISSUE THREAD

**Issue by richey-v** [cross-language-cpp/djinni-generator#46]
I (@richey-v) posted this question in the Slack forum:
> has anyone tried running their Djinni-generated code with [Google sanitizers](https://github.com/google/sanitizers) or something similar?  I am just now doing that and getting failures that include djinni:: calls in the stack trace... the lines above the djinni:: calls are from java-11-openjdk-amd64 so I'm not sure that the failure isn't in the JVM...  I also see leaks that do not include djinni:: calls, so I would think that would point back to the JVM.

This Issue is a recommendation to add run-time QA instrumentation, such as the Google sanitizers mentioned above, to the existing QA processes.

I may be able to post a small example and more information at some point... please ask me for those

**Comment by richey-v** [comment]
Additional tool suggestion...

I just added [Error Prone](https://errorprone.info/) to my project that is using Djinni.  Error Prone hooks the Java compilation process, so is relevant only for languages using `javac`, I would assume.  I'm not familiar enough with Scala compilation to know if Error Prone could be used when building the Djinni generator.

Error Prone didn't find any errors in the Djinni-generated Java, but it was easy enough to add and might be useful in QA.

**Comment by a4z** [comment]
I think we should close this issue, since it is very unlikely it will result in a concrete action on the generator

* every one can compile/run generated code with sanitiser enabled, or what ever tools other languages provide
* we do only generate text in the generator
* the generator is a 1 time execution, and that at build time, even if there would be a flaw, who cares as long as the generated code looks as it should, the generator is not a tool executed in production code, it's a build requirement
* it seems unlikely that there will be any action following up the ticket
* a issue like that might fit to the support lib, but not the generator
* general ideas are better discussed in the newly created discussion forum here on github, https://github.com/cross-language-cpp/djinni-generator/discussions, or on slack, than in the issue section

If no one has anything against it, I will close the ticket after a while

**Comment by a4z** [comment]
Since I  do not see any viable definition of done for this issue, and I haven't got any feedbacl,  I close it for now.

If you think this topic should have a follow up, please use the [discussion section](https://github.com/cross-language-cpp/djinni-generator/discussions) or the slack channel.

If you can think about a definition of done that can be done, feel free to re-open that issue, or create a new one.
