### ISSUE TITLE
Add --version parameter

### ISSUE THREAD

**Issue by jothepro** [cross-language-cpp/djinni-generator#7]
As a user I'd like to be able to run `djinni --version` to find out the currently installed version. This makes it easier to verify what version has been installed on a system.

One idea on how to achieve this is that on release creation the name of the version tag is somehow injected into the build action.

**Comment by a4z** [comment]
This is a very good idea, adding the version! 

It should be possible to get something like `git describe --long --tags --dirty --always` from the build system and bake that into the build

But this would mean, some one who downloads the source tag.gz, and build from that archive, will get a different version, or no at all, even if it is the same ......
So that's difficult 

But, we could tag the version in the build script, and check the output form `git describe .....` that we used the right info and have not forgotten to update this in the build script. This will require more manual interaction, but will then work for all use cases
